name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Initialize and activate virtual environment
        run: |
          uv sync --all-extras --dev
      - name: Test with pytest
        run: |
          uv run pytest tests
